openapi: 3.0.0
info:
  description: API specification for Explorer REST API. See <a target=_blank
    href='http://explorer.dmz.teco.edu/api/docs/db'>DB</a> for the database schema.
    Go to <a href="http://explorer.dmz.teco.edu">explorer.dmz.teco.edu</a> to try it out!
    Backend documentation can be found <a href="http://explorer.dmz.teco.edu/api/docs">here</a>.
  version: 1.0.0
  title: Explorer Auth
servers:
  - url: http://explorer.dmz.teco.edu
tags:
  - name: auth
    description: authentication api
  - name: 2FA
    description: two factor authentication
  - name: user
    description: user management
paths:
  # auth paths
  /auth/register:
    post:
      tags:
      - auth
      summary: Register a new user
      description: Register a new user with email and password 
      operationId: registerNewUser
      requestBody:
        description: Registers a new user with email and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    description: Success message
                    example: Successfully created user!
        '500':
          description: Email already exists

  /auth/unregister:
    post:
      tags:
      - auth
      summary: Unregister a user
      description: Unregister a user. Uses e-mail in body to confirm
      operationId: unregisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user to delete (must match the auth - token)
                  example: test@teco.edu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: 
                  message:
                    type: string
                    description: Success message
                    example: Deleted user with e-mail test@teco.edu
        '401':
          description: Unauthorized
        '500':
          description: Email already exists
  /auth/login:
    post:
      tags:
      - auth
      summary: Log in user
      description: Log in user and returns access_token
      operationId: loginUser
      requestBody:
        description: Log in a user with email and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthObject'
        '404':
          description: User not found
        '400':
          description: Password not correct

  /auth/refresh:
    post:
      tags:
      - auth
      summary: Login with refresh - token
      description: Login with refresh - token and return jwt token
      operationId: refreshUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  description: The bearer refresh - token
                  example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZGQ4OWEwOTU3MzllMDAxOWI2NDE5YSIsImlhdCI6MTU3NDc5OTc4NSwiZXhwIjoxNTc1MDU4OTg1fQ.cSTapFKpbTirbx0qgwiiRVXbev2pvtKHfZokFemEfAg
      responses:
        '200':
          description: OK
        '401':
          description: Token revoked or expired

  /auth/authenticate:
    post:
      tags:
        - auth
      summary: Checks if loing - token is valid
      operationId: authenticate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: True if the token is valid
                    example: true
                  userIds:
                    type: object
                    description: The userId of the user to the login-token
                    example: 602274d7236130a88756f1e3
                  role:
                    type: string
                    description: The role of the user
                    example: 'user'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
      - access_token: []


  
  /auth/2fa/init:
    post:
      tags:
        - 2FA
      summary: Initializes 2FA
      operationId: init2FA
      responses:
        '200':
          description: OK
          content:
            image/png:
              schema:
                type: string
                description: base64 encoded image for the 2FA qr-code
                example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAAAklEQVR4AewaftIAAAeESURBVO3BQY4kRxLAQDLR//8yV0c/BZCo6tEo1s3sH6x1iYe1LvKw1kUe1rrIw1oXeVjrIg9rXeRhrYs8rHWRh7Uu8rDWRR7WusjDWhd5WOsiD2td5GGti/zwIZU/qWJSmSreUJkq3lCZKiaVqWJSeaNiUpkqTlROKiaVP6niEw9rXeRhrYs8rHWRH76s4ptUPqEyVZyoTBVvqEwVk8obFZPKVPGJijcqvknlmx7WusjDWhd5WOsiP/wylTcq3qiYVN6omFQmlTcqTiomlaliUpkqJpU3Kr5J5Y2K3/Sw1kUe1rrIw1oX+eE/TmWq+KaKSWWqmFSmiknljYqTiknl/9nDWhd5WOsiD2td5If/uIoTlaniDZVPqLyhclLxRsWJylTxX/aw1kUe1rrIw1oX+eGXVfybKk5UpooTlUllqjhRmSomlTdUPlHxiYq/ycNaF3lY6yIPa13khy9T+ZNUpopJZap4Q2WqmFROVKaKSWWqmFTeqJhUpopJZao4UfmbPax1kYe1LvKw1kV++FDF30TlRGWqmFSmijdU3qh4Q+UTKm9U/Jc8rHWRh7Uu8rDWRX74kMpUMamcVEwqb1R8QmWq+ETFicpU8UbFpDKpvFFxojJVnKhMFZPKScUnHta6yMNaF3lY6yI//GEVb1RMKpPKJyomld9UcaLyTRUnKlPFVPGbKr7pYa2LPKx1kYe1LvLDH6ZyUjGpTBWTylQxqbxRcaIyVUwqJxWTylTxRsWJylQxVZyofEJlqvhND2td5GGtizysdZEfPlQxqZxUnKhMFScVk8pUMam8ofJGxYnKVHGiclIxqUwVk8pUMamcVEwqf5OHtS7ysNZFHta6iP2DX6RyUjGpfKJiUjmpOFGZKiaVk4pJ5aTiDZU3Kt5QmSomlW+q+MTDWhd5WOsiD2td5IcPqUwVU8WJylRxojJVTCpTxRsqU8WkclLxCZWp4qRiUpkqJpWpYlL5RMUbKt/0sNZFHta6yMNaF/nhD1OZKiaVN1SmiknljYqTikllUvkmlaniExWTylRxovKGyknFNz2sdZGHtS7ysNZFfvhQxYnKVHFScaLym1R+U8Wk8obKScWkclIxqZxUTConFZPKb3pY6yIPa13kYa2L/PAhlaliqnhD5aTiRGWqmFROKiaVqWJS+UTFpDJVTConKlPFJyomlaniRGWqmFSmik88rHWRh7Uu8rDWRX74MpWTipOKN1ROVN5QmSreqPhNFScqJyonFZ9QOVH5TQ9rXeRhrYs8rHWRHz5UcaJyovJGxRsVk8onVL5J5RMqU8VJxYnKVDFVnFScqPymh7Uu8rDWRR7WusgPH1KZKt6oeEPlpGJSmSomlTcqTlQ+UfFGxYnKVDGpTBWTyicqpopJ5Zse1rrIw1oXeVjrIj/8YSpTxaRyUjGpTConKlPFpPKGyicqJpWp4kRlqnijYlKZKk5UpooTld/0sNZFHta6yMNaF/nhQxWTyhsqJxWTylQxqZxUTCpTxScqJpVPqJxUnFScqHyiYlKZKk4qvulhrYs8rHWRh7Uu8sOHVKaKSWWqmFSmiknlRGWqmFROKiaVk4oTlaniROWkYlKZVE4qTio+ofI3eVjrIg9rXeRhrYvYP/hFKlPFJ1ROKt5QmSq+SeUTFScqb1R8QuWbKr7pYa2LPKx1kYe1LvLDh1SmiqliUpkqTlROKr5J5Y2KNyomlW+qOFGZKk5U3qiYVKaK3/Sw1kUe1rrIw1oX+eFDFScqU8WkclJxojJV/KaKSeUTFScqU8WJyknFico3VUwqJxWfeFjrIg9rXeRhrYv88GUqU8WkMlWcqJxUvKEyVZyoTCpvVJyoTBVTxaQyVUwq31TxhspUcVLxTQ9rXeRhrYs8rHWRHz6kMlV8QmWqmFROVKaKqeITFZPKVPFGxaQyVZyoTBVvqEwVk8pJxVTxb3pY6yIPa13kYa2L2D/4RSpTxYnKScU3qUwVk8pJxYnKVHGiclJxojJVnKj8myq+6WGtizysdZGHtS7ywy+reKPiDZWpYlKZKqaKb1KZKk5UpopJZVL5hMpJxRsqb1RMKlPFJx7WusjDWhd5WOsiP3xI5U+qeKPiROWkYlL5N1VMKlPFScWkcqIyVZxU/Jse1rrIw1oXeVjrIvYPPqAyVXyTylQxqbxR8YbKGxUnKm9UfELljYo3VE4q/qSHtS7ysNZFHta6yA+/TOWNijcqJpVPqEwVk8pUcaJyUnGiMlVMKlPFScWkMqn8JpWp4pse1rrIw1oXeVjrIj/8x6mcVLxR8QmVN1S+SWWq+KaKSeVv8rDWRR7WusjDWhf54TIV36QyVUwqU8Wk8kbFpDKpTBWTyonKJ1ROKiaVP+lhrYs8rHWRh7Uu8sMvq/hNFd+k8jepmFQmlROVqeITKlPFpHJS8Zse1rrIw1oXeVjrIj98mcqfpHJSMamcVJyoTBWTyknFpHKiMlWcqPzNVE4qPvGw1kUe1rrIw1oXsX+w1iUe1rrIw1oXeVjrIg9rXeRhrYs8rHWRh7Uu8rDWRR7WusjDWhd5WOsiD2td5GGtizysdZGHtS7yPx44za4HH8iaAAAAAElFTkSuQmCC"
        '404':
          description: Unauthorized
      security:
      - access_token: []
  
  /auth/2fa/verify:
    post:
      tags:
        - 2FA
      summary: Verifies 2FA identiy
      operationId: verify2FA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: number
                  description: the 2fa token comming form the 2fa app
                  example: 123456
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthObject'
        '401':
          description: Unauthorized
      security:
      - access_token: []

  /auth/2fa/reset:
    post:
      tags:
        - 2FA
      summary: Removes 2fa
      operationId: reset2FA
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully reset TwoFactorAuthentication"
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
      - access_token: []

  /auth/id:
    post:
      tags:
        - user
      summary: Maps userNames to userIds
      description: Maps userNames to userIds. The output has the same order as the input
      operationId: /id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: The userIds
                example: testUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: The userIds
                  example: 602274d7236130a88756f1e3
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: Some users could not be found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
      - access_token: []

  /auth/userName:
    post:
      tags:
        - user
      summary: Maps userIds to userNames
      description: Maps userIds to userNames. The output has the same order as the input
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: The userIds
                  example: 602274d7236130a88756f1e3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: The userIds
                  example: testUser
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: Some userIds could not be found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
      - access_token: []

  /auth/changeMail:
    post:
      tags:
        - user
      summary: Change e-mail of own user
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The new e-mail of the user
                  example: "test@teco.edu"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Changed e-mail address from test@teco.edu to test2@teco.edu
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: test2@teco.edu is not a valid e-mail address
        '500':
          description: Internal server error
      security:
      - access_token: []

  /auth/changeUserName:
    post:
      tags:
        - user
      summary: Change userName of own user
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: The new userName of the user
                  example: "testUser2"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Changed userName from testUser to testUser2
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: Username already exists
        '500':
          description: Internal server error
      security:
      - access_token: []              

  /auth/changePassword:
    post:
      tags:
        - user
      summary: Change password of own user
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: The current password
                  example: testPassword
                newPassword:
                  type: string
                  description: The new password
                  example: newTestPassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Changed password
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: Provide the current password and the new password
        '500':
          description: Internal server error
      security:
      - access_token: []

          
        

          

                




  

components:
  securitySchemes:
    access_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Please provide a valid JWT token
      headers:
        WWW_Authenticate:
          schema:
            type: string
    NotFoundError:
      description: Not Found
      headers:
        WWW_Authenticate:
          schema:
            type: string
    InternalServerError:
      description: Not Found
      headers:
        WWW_Authenticate:
          schema:
            type: string
  schemas:
  # Authentication Schemas
    RegisterUser:
      type: object
      properties:
        email:
          type: string
          description: email for user account
          example: test@teco.edu
        userName:
          type: string
          description: userName for user account
          example: testUser
        password:
          type: string
          description: password for user account
    LoginUser:
      type: object
      properties:
        email:
          type: string
          description: email of user or userName
          example: test@teco.edu OR testUser
        password:
          type: string
          description: password for user account
          example: examplePW123
      xml:
        name: UserforAuth
    AuthObject:
      type: object
      properties:
        access_token:
          type: string
          description: Bearer JWT Token
          example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZGQ4OWEwOTU3MzllMDAxOWI2NDE5YSIsImlhdCI6MTU3NDc5OTc4NSwiZXhwIjoxNTc1MDU4OTg1fQ.cSTapFKpbTirbx0qgwiiRVXbev2pvtKHfZokFemEfAg
        refresh_token:
          type: string
          description: Refresh JWT Token - Not in us
          example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZGQ4OWEwOTU3MzllMDAxOWI2NDE5YSIsImlhdCI6MTU3NDc5OTc4NSwiZXhwIjoxNTc1MDU4OTg1fQ.cSTapFKpbTirbx0qgwiiRVXbev2pvtKHfZokFemEfAg
        twoFactorEnabled:
          type: boolean
          description: Indicates wether 2fa is enabled on this user
          example: false
        twoFactorVerified:
          type: boolean
          description: Indicates wether 2fa is verified on this user
          example: false
      xml:
        name: AuthObject